### ISSUE TITLE
API with callbacks

### ISSUE THREAD

**Issue by ibotlold** [jsightapi/specification#7]
Hello guys! I am trying to use JSight. And here is my situation:
I have API where users can manipulate my app with provided webhook. I need to describe communication interface. Is there any resource, thoughts how to do this in JSight?

FE, client register webhook `https://company.com/api/messages`. And when event occurs i reply to that url
```json
{
  "order": 234234,
  "operator": "service1",
  "docs": "http://s3.aws.com/docs/some-uuid"
}
```
And client should respond something like
```json
{
  "gateway": "customer",
  "expire": "2023-11-11T11:30:00.000Z"
}
```

My idea is to create separate files for every webhook. Wonder if it possible document API in a single jsight file

**Comment by andrew-platonov** [comment]
Hello, Kirill! Do you mean the corresponding [callbacks](https://swagger.io/docs/specification/callbacks/) in OpenAPI? If yes, than we have not implemented such a function in JSight yet. It is in our roadmap, though.

Now as a work-around you can mention the callback subscripton feature in comments, see an example here: https://editor.jsight.io/r/rjEwe6J/1
